# SmartFlush Predictive Modeling System configuration

project:
  name: "SmartFlush Predictive Modeling System"
  version: "0.1.0"

paths:
  data_dir: "data"
  notebooks_dir: "notebooks"
  reports_dir: "reports"
  results_dir: "results"
  logs_dir: "logs"

data:
  files:
    - "Combined_Data.xlsx"
    - "mon_fichier.xlsx"
  sheet_name: null            # Override per file if needed
  target_column: "flush_volume_class"
  categorical_features: ["case_of_flush"]
  datetime_columns: []
  test_size: 0.2
  random_state: 42
  stratify: true

preprocessing:
  drop_na: true
  imputation_strategy: "median"
  vif_threshold: 8.0
  include_residual_features: true
  residual_reference_model: "ridge"
  standardize: true
  scaler: "standard"          # standard, robust, minmax
  polynomial_degree: 2
  interaction_only: false
  target_offset: 1.0

eda:
  chi2_alpha: 0.05
  pearson_method: "pearson"
  pairplot_sample_size: 2000
  boxplot_targets:
    - "case_of_flush"
    - "flush_volume_class"
  heatmap_figsize: [12, 8]
  save_plots: true

grid_search:
  cv_folds: 5
  scoring: "neg_mean_absolute_error"
  n_jobs: -1
  refit_metric: "mae"

models:
  ridge:
    enabled: true
    add_constant: 1.0
    grid:
      alpha: [0.1, 1.0, 10.0, 100.0]
      fit_intercept: [true]
  multinomial_logistic:
    enabled: true
    add_constant: 1.0
    grid:
      C: [0.1, 1.0, 10.0]
      penalty: ["l2"]
      solver: ["lbfgs"]
      max_iter: [500]
  multinomial_logistic_prob:
    enabled: true
    thresholds: [0.4, 0.5, 0.6]
  svc:
    enabled: true
    kernels: ["linear", "poly"]
    grid:
      C: [0.1, 1.0, 10.0]
      degree: [1, 2, 3]
      gamma: ["scale"]
  svc_prob:
    enabled: true
    thresholds: [0.45, 0.5, 0.55]
  ann:
    enabled: true
    architecture: [128, 64, 32]
    dropout_rate: 0.2
    learning_rate: 0.001
    epochs: 200
    batch_size: 64
    validation_split: 0.2
    patience: 20

evaluation:
  safe_flush_threshold: 0.95
  mae_unit: "liters"
  competitor:
    accuracy: 0.31
    safe_accuracy: 0.56
    mae: 0.93
  hotel_scenario:
    rooms: 100
    flushes_per_day: 5
    water_cost_eur_per_1000l: 4.0
  probability_thresholds: [0.4, 0.5, 0.6]
  volume_mapping:
    1: 1.5
    2: 1.9
    3: 2.2
    4: 2.6
    5: 3.0
    6: 3.4
    7: 3.8
    8: 4.3
    9: 4.7
    10: 5.4
    11: 6.1

outputs:
  save_models: true
  save_learning_curves: true
  save_tables: true
  figures_dir: "results/figures"
  tables_dir: "results/tables"
  models_dir: "results/models"
  reports_dir: "reports"

logging:
  level: "INFO"
  format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
  file_name: "smartflush.log"

stages:
  run_data_loading: true
  run_eda: true
  run_modeling: true
  run_reporting: true
